--- 
- name: enable internet services
  hosts: all
  become: yes
  tasks: 
    - name: installed all package
      yum:
        name:
          - firewalld
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
        state: latest

    - name: the firewalld service is enabled and running
      service: 
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits access is allowed http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    

    


